'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { fork } = require('node:child_process');
const { once } = require('node:events');
const Database = require('better-sqlite3');
const { createRecoveryActivityRepository } = require('../src/repositories/v2/recoveryActivityRepository');

test('recovery ownership excludes another connection/process and reclaims only after owner exits', async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lmd-recovery-ownership-'));
  const filename = path.join(root, 'test.sqlite');
  const database = new Database(filename);
  t.after(() => database.close());
  database.exec(fs.readFileSync(path.join(__dirname, '../migrations/v2/0039_recovery_activity_ownership.sql'), 'utf8'));
  const key = 'remote/00000000-0000-4000-8000-000000000001';
  const otherDatabase = new Database(filename);
  t.after(() => otherDatabase.close());
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const parent = createRecoveryActivityRepository(database);
  const other = createRecoveryActivityRepository(otherDatabase);
  const held = parent.acquire(key);
  assert.ok(held);
  assert.equal(other.acquire(key), null);
  held.release();
  const child = fork(path.join(__dirname, 'helpers/recoveryActivityChild.cjs'), [filename, key], { windowsHide: true });
  t.after(() => { if (child.exitCode === null) child.kill(); });
  await once(child, 'message');
  assert.equal(parent.acquire(key), null);
  const exited = once(child, 'exit');
  child.send('exit');
  assert.deepEqual(await exited, [0, null]);
  const reclaimed = parent.acquire(key);
  assert.ok(reclaimed);
  assert.equal(other.acquire(key), null);
  reclaimed.release();
  assert.equal(database.prepare('SELECT count(*) FROM recovery_activity_ownership').pluck().get(), 0);
});
